# Generated by Django 3.1.6 on 2021-03-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productpromotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercomment',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
