# Generated by Django 3.1.6 on 2021-03-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210324_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaproduct',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
