# Generated by Django 3.1.6 on 2021-03-13 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_merge_20210311_0114'),
        ('store', '0005_merge_20210311_1830'),
        ('store', '0006_auto_20210311_2013'),
    ]

    operations = [
    ]
