# Generated by Django 3.1.6 on 2021-03-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_cl', '0002_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
